[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unicode-3.0",
    "GPL-3.0",
    "AGPL-3.0",
    "Apache-2.0 WITH LLVM-exception",
    "MPL-2.0",
    "ISC",
    "Zlib",
    "WTFPL",
    "OpenSSL",
    "CC0-1.0",
]

unused-allowed-license = "warn"
confidence-threshold = 0.95

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[advisories]
ignore = [
    # ring is unmaintained
    # we do not use ring for anything except for http3 testing in scuffle-http.
    # Unfortunately reqwest uses ring for http3.
    # See https://github.com/seanmonstar/reqwest/issues/2566
    "RUSTSEC-2025-0007",
]
