[workspace]
allow_dirty = true
changelog_update = true
git_release_body = """
See [crates.io](https://crates.io/crates/{{ package }}/{{ version }})

See [docs.rs](https://docs.rs/{{ package }}/{{ version }})

{{ changelog }}
{% if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
"""

[[package]]
name = "scuffle-workspace-hack"
release = false

[[package]]
name = "scuffle-ffmpeg"
publish_features = ["build"]

[changelog]
body = """

## [{{ version | trim_start_matches(pat="v") }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}

"""
