[workspace]
allow_dirty = true
changelog_update = true
git_release_body = """
[<img alt="crates.io" src="https://img.shields.io/badge/crates.io-v{{ version }}-orange?labelColor=5C5C5C" height="20">](https://crates.io/crates/{{ package }}/{{ version }}) [<img alt="docs.rs" src="https://img.shields.io/badge/docs.rs-v{{ version }}-blue?labelColor=5C5C5C" height="20">](https://docs.rs/{{ package }}/{{ version }})

{{ changelog }}
{% if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
"""

[[package]]
name = "scuffle-workspace-hack"
release = false

[[package]]
name = "scuffle-ffmpeg"
publish_features = ["build"]

[changelog]
body = """

## [{{ version | trim_start_matches(pat="v") }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}

"""
