[[scuffle-h264]]
category = "fix"
description = "Fixes a bug with removing the emu prevention byte causing other bytes to be lost by accident"
breaking = true
authors = ["@philipch07"]

[[scuffle-h264]]
category = "refactor"
description = "Refactored how tests work so they work like the tests in our other crates"
breaking = true
authors = ["@philipch07"]

[[scuffle-h264]]
category = "refactor"
description = "Refactored sps output and input to use nutype enums"
breaking = true
authors = ["@philipch07"]

[[scuffle-h264]]
category = "test"
description = "Improved test coverage for sps and config"
breaking = false
authors = ["@philipch07"]

[[scuffle-h264]]
category = "docs"
description = "Added docs for the crate, sps, and config"
breaking = false
authors = ["@philipch07"]

