[[scuffle-ffmpeg]]
category = "feat"
description = "add support for arm64 builds"
authors = ["@TroyKomodo"]

[[postcompile]]
category = "feat"
description = "add support for windows builds"
authors = ["@TroyKomodo"]

[[scuffle-pprof]]
category = "docs"
description = "document lack of windows support"
authors = ["@TroyKomodo"]
