[[scuffle-metrics]]
category = "chore"
description = "Update prometheus-client to 0.23"
authors = ["@TroyKomodo"]
breaking = true

[[scuffle-bootstrap-telemetry]]
category = "chore"
description = "Update prometheus-client to 0.23"
authors = ["@TroyKomodo"]
breaking = true
