[[scuffle-h264]]
category = "refactor"
description = "AVCDecoderConfigurationRecord now uses actual SpsExtended struct (we intentionally do not let it use the Sps struct)"
breaking = true
authors = ["@philipch07"]

[[scuffle-h264]]
category = "refactor"
description = "Refactored Sps to be its own module with each struct having its own file"
breaking = true
authors = ["@philipch07"]

[[scuffle-h264]]
category = "fix"
description = "Fixes a bug with the AVCDecoderConfigurationRecord size not being computed correctly"
breaking = true
authors = ["@philipch07"]

[[scuffle-h264]]
category = "fix"
description = "Fixes a bug with the AVCDecoderConfigurationRecord not being built correctly due to byte misalignment"
breaking = true
authors = ["@philipch07"]

[[scuffle-h264]]
category = "feat"
description = "All sps structs can now be \"built\", that is, they can now go from a struct back into a bytestream"
breaking = false
authors = ["@philipch07"]

[[scuffle-h264]]
category = "feat"
description = "Parsing and building Sps can now use the `EmulationPreventionIo` wrapper to automatically handle emulation prevention bytes"
breaking = false
authors = ["@TroyKomodo"]

[[scuffle-h264]]
category = "feat"
description = "All sps structs now have functions to retrieve their bit/byte sizes"
breaking = false
authors = ["@philipch07"]

[[scuffle-expgolomb]]
category = "feat"
description = "Added 2 functions to be able to get the bit size of un/signed expgolombs without having to write them"
breaking = false
authors = ["@philipch07"]
