[[scuffle-aac]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-amf0]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-av1]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-batching]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-bootstrap]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-bootstrap-derive]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-bootstrap-telemetry]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-bytes-util]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-context]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-expgolomb]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-ffmpeg]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-flv]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-future-ext]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-h264]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-h3-webtransport]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-http]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-metrics]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-metrics-derive]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-mp4]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[nutype-enum]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[postcompile]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-pprof]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-rtmp]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-settings]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-signal]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]

[[scuffle-transmuxer]]
category = "chore"
description = "update to rust edition 2024"
authors = ["@TroyKomodo"]
