[[scuffle-ffmpeg]]
category = "feat"
description = "add support for arm64 builds"
authors = ["@TroyKomodo"]

[[scuffle-ffmpeg]]
category = "feat"
description = "add support for windows builds"
authors = ["@TroyKomodo"]

[[scuffle-ffmpeg]]
category = "fix"
description = "fix windows memory corruption issue"
authors = ["@TroyKomodo"]

[[postcompile]]
category = "feat"
description = "add support for windows builds"
authors = ["@TroyKomodo"]

[[scuffle-pprof]]
category = "docs"
description = "document lack of windows support"
authors = ["@TroyKomodo"]

[[scuffle-bootstrap-telemetry]]
category = "docs"
description = "document pprof is not supported on windows"
authors = ["@TroyKomodo"]

[[scuffle-http]]
category = "fix"
description = "fix windows blocking event-loop when running a http server"
authors = ["@TroyKomodo"]

[[scuffle-signal]]
category = "docs"
description = "document signal is not supported on windows"
authors = ["@TroyKomodo"]
