[[scuffle-bootstrap-metrics]]
category = "chore"
description = "Update OpenTelemetry to 0.28"
authors = ["@TroyKomodo"]
breaking = true

[[scuffle-metrics]]
category = "chore"
description = "Update OpenTelemetry to 0.28"
authors = ["@TroyKomodo"]
breaking = true
