name: Test
inputs:
  pr_number:
    description: "The PR number"
    required: true
  codecov_token:
    description: "The Codecov token"
    required: true
  artifact_name:
    description: "The name of the artifact to upload"
    required: false
  deploy_docs:
    description: "Whether to deploy the docs"
    required: false
runs:
  using: "composite"
  steps:
    - name: Build docs
      run: |
        set -xeo pipefail
        cargo doc --no-deps --all-features

    - name: Insert custom html for PR
      if: ${{ inputs.pr_number }}
      run: .github/scripts/patch-docs.sh ${{ github.event.repository.html_url }} ${{ env.SHA }} ${{ inputs.pr_number }}

    - name: Insert custom html for merge
      run: .github/scripts/patch-docs.sh ${{ github.event.repository.html_url }} ${{ env.SHA }}

    - name: Upload docs
      uses: actions/upload-artifact@v4
      if: ${{ inputs.artifact_name }}
      with:
        name: ${{ inputs.artifact_name }}
        path: target/doc

    - name: Deploy
      if: ${{ inputs.deploy_docs }}
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_DOCS_API_KEY }}
        accountId: ${{ secrets.CF_DOCS_ACCOUNT_ID }}
        command: pages deploy --project-name=scuffle-docrs --branch=pr/${{ inputs.pr_number }} --commit-hash=${{ env.SHA }} --commit-dirty=true ./target/doc
