name: Hakari
runs:
  using: "composite"
  steps:
    - name: Make sure Hakari is up-to-date
      shell: bash
      run: |
        set -xeo pipefail

        cargo hakari manage-deps --dry-run
        cargo hakari generate --diff
        cargo hakari verify
