name: Grind
inputs:
  target:
    description: "The target to run Valgrind on"
    required: true
  env:
    description: "The environment variables to set"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Valgrind
      shell: bash
      run: |
        set -xeo pipefail
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends valgrind

    - name: Setup env
      if: ${{ inputs.env }}
      shell: bash
      run: |
        set -eo pipefail
        env_json=$(cat <<ENV_END_OF_FILE
        ${inputs.env}
        ENV_END_OF_FILE
        )
        for key in $(echo "$env_json" | jq -r 'keys[]'); do
            expanded_key=$(eval echo "$key")
            value=$(echo "$env_json" | jq -r --arg key "$key" '.[$key]')
            expanded_value=$(eval echo "$value")
            echo "$expanded_key=$expanded_value" >> $GITHUB_ENV
            echo "Setting $expanded_key to $expanded_value"
        done


    - name: Run valgrind
      shell: bash
      env:
        RUSTFLAGS: "--cfg reqwest_unstable --cfg valgrind"
      run: cargo nextest run --all-features --no-fail-fast --profile ci
