[package]
name = "transmuxer"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
byteorder = "1.5"
bytes = "1.5"

h264 = { path = "../h264" }
h265 = { path = "../h265" }
scuffle-aac = { path = "../aac" }
mp4 = { path = "../mp4" }
scuffle-av1.workspace = true
scuffle-flv.workspace = true
scuffle-amf0.workspace = true
scuffle-bytes-util.workspace = true
scuffle-workspace-hack.workspace = true

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
