[package]
name = "transmuxer"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
byteorder = "1.5"
bytes = "1.5"

bytesio = { path = "../bytesio" }
h264 = { path = "../h264" }
h265 = { path = "../h265" }
av1 = { path = "../av1" }
aac = { path = "../aac" }
amf0 = { path = "../amf0" }
flv = { path = "../flv" }
mp4 = { path = "../mp4" }
scuffle-workspace-hack.workspace = true

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
