[package]
name = "scuffle-future-ext"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1", features = ["time"] }
scuffle-workspace-hack.workspace = true
