[package]
name = "mp4"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
byteorder = "1.5"
bytes = "1.5"
fixed = "1.24"
paste = "1.0"

bytesio = { path = "../bytesio", default-features = false, features = []}
h264 = { path = "../h264" }
h265 = { path = "../h265" }
av1 = { path = "../av1" }
aac = { path = "../aac" }
scuffle-workspace-hack.workspace = true

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
