name: Setup FFmpeg
description: Installs FFmpeg on the system
runs:
  using: "composite"
  steps:
    - name: Install System Dependencies
      shell: bash
      run: |
        set -xeo pipefail
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends nasm

    - name: Install ffmpeg
      shell: bash
      run: |
        set -xeo pipefail

        curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-linux64-gpl-shared-7.1.tar.xz -o ffmpeg.tar.xz
        tar -xvf ffmpeg.tar.xz

        sudo mv ffmpeg-n7.1-latest-linux64-gpl-shared-7.1/include/* /usr/include
        sudo mv ffmpeg-n7.1-latest-linux64-gpl-shared-7.1/lib/* /usr/local/lib
        sudo mv ffmpeg-n7.1-latest-linux64-gpl-shared-7.1/bin/* /usr/local/bin
        sudo rm -rf ffmpeg-n7.1-latest-linux64-gpl-shared-7.1
        sudo rm -rf ffmpeg.tar.xz
        sudo ldconfig
