name: Setup FFmpeg
description: Installs FFmpeg on the system
inputs:
  arch:
    description: "The architecture the runner is running on"
    required: false
    default: ${{ runner.arch }}
  os:
    description: "The operating system the runner is running on"
    required: false
    default: ${{ runner.os }}
  version:
    description: "The version of FFmpeg to install"
    required: false
    default: "7.1"
runs:
  using: "composite"
  steps:
    - name: Install System Dependencies
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        set -xeo pipefail
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends nasm

    - name: Determine File
      id: file
      shell: bash
      run: |
        set -xeo pipefail

        ARCH='${{ inputs.arch || runner.arch }}'
        OS='${{ inputs.os || runner.os }}'

        case "$ARCH" in
          x86_64|amd64|X64) FF_ARCH="64" ;;
          aarch64|arm64|ARM64) FF_ARCH="arm64" ;;
          *) echo "Unsupported architecture: $ARCH" && exit 1 ;;
        esac

        case "$OS" in
          linux|Linux|LINUX) FF_OS="linux" && FF_EXT="tar.xz" ;;
          windows|Windows|WINDOWS) FF_OS="win" && FF_EXT="zip" ;;
          *) echo "Unsupported operating system: $OS" && exit 1 ;;
        esac

        case "${{ inputs.version || '7.1' }}" in
          "7.1") FILE="ffmpeg-n7.1-latest-${FF_OS}${FF_ARCH}-gpl-shared-7.1.${FF_EXT}" ;;
          "6.1") FILE="ffmpeg-n6.1-latest-${FF_OS}${FF_ARCH}-gpl-shared-6.1.${FF_EXT}" ;;
          "master") FILE="ffmpeg-master-latest-${FF_OS}${FF_ARCH}-gpl-shared.${FF_EXT}" ;;
          *) echo "Unsupported version: ${{ inputs.version }}" && exit 1 ;;
        esac

        FF_URL="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/${FILE}"

        echo "Downloading FFmpeg from $FF_URL"
        curl -L "$FF_URL" -o ffmpeg.${FF_EXT}

        case "${{ runner.os }}" in
          Linux)
            tar -xvf ffmpeg.${FF_EXT}
            FFMPEG_ROOT="/usr/local"
          Windows)
            unzip ffmpeg.${FF_EXT}
            FFMPEG_ROOT="C:/ffmpeg"
        esac

        sudo mkdir -p ${FFMPEG_ROOT}/{include,lib,bin}
        sudo mv ffmpeg-*/include/* ${FFMPEG_ROOT}/include
        sudo mv ffmpeg-*/lib/* ${FFMPEG_ROOT}/lib
        sudo mv ffmpeg-*/bin/* ${FFMPEG_ROOT}/bin

        if [ "${{ runner.os }}" = "Linux" ]; then
          # Update the dynamic linker cache
          sudo ldconfig
        fi

        echo "FFMPEG_ROOT=${FFMPEG_ROOT}" >> $GITHUB_ENV
        echo "FFMPEG_INCLUDE_DIR=${FFMPEG_ROOT}/include" >> $GITHUB_ENV
        echo "FFMPEG_LIBRARY_DIR=${FFMPEG_ROOT}/lib" >> $GITHUB_ENV
        echo "FFMPEG_LIBS_DIR=${FFMPEG_ROOT}/lib" >> $GITHUB_ENV
        echo "FFMPEG_BIN_DIR=${FFMPEG_ROOT}/bin" >> $GITHUB_ENV
        echo "FFMPEG_DLL_PATH=${FFMPEG_ROOT}/lib" >> $GITHUB_ENV
        echo "${FFMPEG_ROOT}/bin" >> $GITHUB_PATH
        echo "${FFMPEG_ROOT}/lib" >> $GITHUB_PATH
        echo "${FFMPEG_ROOT}/include" >> $GITHUB_PATH

        echo "FFmpeg installed successfully"
