name: Setup FFmpeg
description: Installs FFmpeg on the system
inputs:
  architecture:
    description: "The architecture the runner is running on"
    required: false
  version:
    description: "The version of FFmpeg to install"
    required: false
    default: "7.1"
runs:
  using: "composite"
  steps:
    - name: Install System Dependencies
      shell: bash
      run: |
        set -xeo pipefail
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends nasm

    - name: Install FFmpeg
      shell: bash
      run: |
        set -xeo pipefail

        ARCH=$(uname -m)
        if [[ -z "${{ inputs.architecture }}" ]]; then
          case "$ARCH" in
            x86_64) FF_ARCH="linux64" ;;
            aarch64) FF_ARCH="linuxarm64" ;;
            *) echo "Unsupported architecture: $ARCH" && exit 1 ;;
          esac
        fi

        if [[ "${{ inputs.version }}" == "master" ]]; then
          FF_VERSION="master"
          FF_SMALL_VERSION=""
        else
          FF_VERSION="n${{ inputs.version }}-latest"
          FF_SMALL_VERSION="${{ inputs.version }}"
        fi

        FF_URL="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-${FF_VERSION}-${FF_ARCH}-gpl-shared-${FF_SMALL_VERSION}.tar.xz"

        echo "Downloading FFmpeg from $FF_URL"
        curl -L "$FF_URL" -o ffmpeg.tar.xz
        tar -xvf ffmpeg.tar.xz

        sudo mv ffmpeg-*/include/* /usr/local/include
        sudo mv ffmpeg-*/lib/* /usr/local/lib
        sudo mv ffmpeg-*/bin/* /usr/local/bin
        sudo rm -rf ffmpeg-* ffmpeg.tar.xz
        sudo ldconfig
