name: Setup FFmpeg
description: Installs FFmpeg on the system
inputs:
  arch:
    description: "The architecture the runner is running on"
    required: false
  version:
    description: "The version of FFmpeg to install"
    required: false
    default: "7.1"
runs:
  using: "composite"
  steps:
    - name: Install System Dependencies
      shell: bash
      run: |
        set -xeo pipefail
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends nasm

    - name: Determine File
      id: file
      run: |
        set -xeo pipefail

        ARCH='${{ inputs.arch }}'
        if [[ -z "$ARCH" ]]; then
          ARCH=$(uname -m)
        fi

        case "$ARCH" in
          x86_64) FF_ARCH="linux64" ;;
          aarch64) FF_ARCH="linuxarm64" ;;
          *) echo "Unsupported architecture: $ARCH" && exit 1 ;;
        esac

        case "${{ inputs.version || '7.1' }}" in
          "7.1") FILE="ffmpeg-n7.1-${FF_ARCH}-gpl-shared-7.1.tar.xz" ;;
          "6.1") FILE="ffmpeg-n6.1-${FF_ARCH}-gpl-shared-6.1.tar.xz" ;;
          "master") FILE="ffmpeg-master-${FF_ARCH}-gpl-shared.tar.xz" ;;
          *) echo "Unsupported version: ${{ inputs.version }}" && exit 1 ;;
        esac

        FF_URL="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/${FILE}"

        echo "Downloading FFmpeg from $FF_URL"
        curl -L "$FF_URL" -o ffmpeg.tar.xz
        tar -xvf ffmpeg.tar.xz

        sudo mv ffmpeg-*/include/* /usr/local/include
        sudo mv ffmpeg-*/lib/* /usr/local/lib
        sudo mv ffmpeg-*/bin/* /usr/local/bin
        sudo rm -rf ffmpeg-* ffmpeg.tar.xz
        sudo ldconfig
