name: Cargo Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight

env:
  RUST_TOOLCHAIN: nightly

jobs:
  cargo-update:
    name: Cargo Update
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Update Cargo.lock
        run: cargo update

      # Check if any files changed
      - name: Check if anything changed
        id: changed
        run: |
          result=$((git diff --exit-code > /dev/null && echo '0') || echo '1')
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Create github PR
        uses: peter-evans/create-pull-request@v7
        if: ${{ steps.changed.outputs.result == 1 }}
        with:
          title: Automated update of Cargo.lock
          body-path: /tmp/pr-body.txt
          branch: automation/cargo-update
          labels: release,automated,change-log-not-required
          commit-message: |
            Automated update of Cargo.lock

            Release triggered by @${{ github.actor }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          sign-commits: true
          reviewers: ${{ github.actor }}
