name: change log

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

env:
  RUST_TOOLCHAIN: nightly
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  check-change-log:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.SHA }}

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          tools: just

      - name: Check change log entry
        run: cargo +${{ env.RUST_TOOLCHAIN }} xtask change-log check-pr ${{ github.event.pull_request.number }} --required=${{ env.REQUIRED  }}
        env:
          REQUIRED: ${{ !contains(github.event.pull_request.labels.*.name, 'change-log-not-required') }}
