name: Crate Releases

on:
  push:
    branches:
      - main

env:
  RUST_TOOLCHAIN: nightly

jobs:
  release:
    name: Release
    runs-on: ubicloud-standard-8
    environment: crates
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup FFmpeg
        uses: ./.github/actions/setup-ffmpeg

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy
          shared-key: clippy
          tools: just,cargo-hakari,release-plz
          cache-backend: ubicloud

      - name: Remove cargo registries
        run: |
          rm -rf ~/.cargo/registry

      - name: Fix workspace deps
        run: cargo +${{ env.RUST_TOOLCHAIN }} xtask workspace-deps

      - name: Cargo Hackari disable
        run: cargo +${{ env.RUST_TOOLCHAIN }} hakari disable

      - uses: fregante/setup-git-user@v2

      - name: Run release-plz
        run: release-plz release --allow-dirty --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --git-token ${{ secrets.GITHUB_TOKEN }}
