name: Crate Releases

on:
  push:
    branches:
      - main
      - troy/ci-tests-deploy

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    environment: crates
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Fix workspace deps
        run: cargo xtask workspace-deps

      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release --allow-dirty
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
