name: Docs Release

on:
  push:
    branches:
      - main
      - test-deploy

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-24.04
    environment: docs.scuffle.rs
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.SHA }}

      - name: Setup nasm
        run: |
          sudo apt-get install nasm

      - uses: dtolnay/rust-toolchain@stable
        id: setup-rust
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rust-docs

      - uses: Swatinem/rust-cache@v2
        id: cache-rust
        with:
          prefix-key: "v0-rust-${{ steps.setup-rust.outputs.cachekey }}"
          shared-key: docs

      - name: Build docs
        run: |
          RUSTDOCFLAGS="-D warnings --cfg docsrs --enable-index-page -Zunstable-options" cargo +${{ env.RUST_TOOLCHAIN }} doc --no-deps --all-features

      - name: Get short commit SHA
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Insert custom html
        run: .github/patch-docs.sh ${{ github.sha }} ${{ env.SHORT_SHA }}

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_DOCS_API_KEY }}
          accountId: ${{ secrets.CF_DOCS_ACCOUNT_ID }}
          command: pages deploy --project-name=scuffle-docrs --branch=main --commit-hash=${{ github.sha }} ./target/doc
