[package]
name = "scuffle-signal"
version = "0.2.1"
edition = "2024"
repository = "https://github.com/scufflecloud/scuffle"
authors = ["Scuffle <opensource@scuffle.cloud>"]
readme = "README.md"
documentation = "https://docs.rs/scuffle-signal"
license = "MIT OR Apache-2.0"
description = "Ergonomic async signal handling."
keywords = ["signal", "async"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)', 'cfg(valgrind)'] }

[dependencies]
tokio = { version = "1", default-features = false, features = ["signal"] }
scuffle-bootstrap = { workspace = true, optional = true }
scuffle-context = { workspace = true, optional = true }
anyhow = { version = "1", optional = true }
scuffle-workspace-hack.workspace = true

[dev-dependencies]
tokio = { version = "1.41.1", features = ["full"] }
tokio-test = "0.4"
futures = "0.3"
scuffle-future-ext.workspace = true
libc = "0.2"
libtest-mimic = "0.8"

[target.'cfg(windows)'.dev-dependencies]
windows = { version = "0.60.0", features = ["Win32_Storage_FileSystem", "Win32_System_Console", "Win32_System_Threading", "Win32_Security", "Win32_System_IO"] }
windows-strings = "0.3"
tokio-stream = { version = "0.1", features = ["sync"] }

[features]
bootstrap = ["scuffle-bootstrap", "scuffle-context", "anyhow", "tokio/macros"]
